// <auto-generated/>
#pragma warning disable CS0618
using Ayllu.Github.Client.Orgs.Item.Docker.Conflicts;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Ayllu.Github.Client.Orgs.Item.Docker
{
    /// <summary>
    /// Builds and executes requests for operations under \orgs\{org}\docker
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DockerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The conflicts property</summary>
        public global::Ayllu.Github.Client.Orgs.Item.Docker.Conflicts.ConflictsRequestBuilder Conflicts
        {
            get => new global::Ayllu.Github.Client.Orgs.Item.Docker.Conflicts.ConflictsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ayllu.Github.Client.Orgs.Item.Docker.DockerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DockerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orgs/{org}/docker", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ayllu.Github.Client.Orgs.Item.Docker.DockerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DockerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orgs/{org}/docker", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
