// <auto-generated/>
#pragma warning disable CS0618
using Ayllu.Github.Client.Advisories;
using Ayllu.Github.Client.App;
using Ayllu.Github.Client.AppManifests;
using Ayllu.Github.Client.Applications;
using Ayllu.Github.Client.Apps;
using Ayllu.Github.Client.Assignments;
using Ayllu.Github.Client.Classrooms;
using Ayllu.Github.Client.Codes_of_conduct;
using Ayllu.Github.Client.Credentials;
using Ayllu.Github.Client.Emojis;
using Ayllu.Github.Client.Enterprises;
using Ayllu.Github.Client.Events;
using Ayllu.Github.Client.Feeds;
using Ayllu.Github.Client.Gists;
using Ayllu.Github.Client.Gitignore;
using Ayllu.Github.Client.Installation;
using Ayllu.Github.Client.Issues;
using Ayllu.Github.Client.Licenses;
using Ayllu.Github.Client.Markdown;
using Ayllu.Github.Client.Marketplace_listing;
using Ayllu.Github.Client.Meta;
using Ayllu.Github.Client.Models;
using Ayllu.Github.Client.Networks;
using Ayllu.Github.Client.Notifications;
using Ayllu.Github.Client.Octocat;
using Ayllu.Github.Client.Organizations;
using Ayllu.Github.Client.Orgs;
using Ayllu.Github.Client.Projects;
using Ayllu.Github.Client.Rate_limit;
using Ayllu.Github.Client.Repos;
using Ayllu.Github.Client.Repositories;
using Ayllu.Github.Client.Search;
using Ayllu.Github.Client.Teams;
using Ayllu.Github.Client.User;
using Ayllu.Github.Client.Users;
using Ayllu.Github.Client.Versions;
using Ayllu.Github.Client.Zen;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Ayllu.Github.Client
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AylluGithubClient : BaseRequestBuilder
    {
        /// <summary>The advisories property</summary>
        public global::Ayllu.Github.Client.Advisories.AdvisoriesRequestBuilder Advisories
        {
            get => new global::Ayllu.Github.Client.Advisories.AdvisoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The app property</summary>
        public global::Ayllu.Github.Client.App.AppRequestBuilder App
        {
            get => new global::Ayllu.Github.Client.App.AppRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The applications property</summary>
        public global::Ayllu.Github.Client.Applications.ApplicationsRequestBuilder Applications
        {
            get => new global::Ayllu.Github.Client.Applications.ApplicationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The appManifests property</summary>
        public global::Ayllu.Github.Client.AppManifests.AppManifestsRequestBuilder AppManifests
        {
            get => new global::Ayllu.Github.Client.AppManifests.AppManifestsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The apps property</summary>
        public global::Ayllu.Github.Client.Apps.AppsRequestBuilder Apps
        {
            get => new global::Ayllu.Github.Client.Apps.AppsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The assignments property</summary>
        public global::Ayllu.Github.Client.Assignments.AssignmentsRequestBuilder Assignments
        {
            get => new global::Ayllu.Github.Client.Assignments.AssignmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The classrooms property</summary>
        public global::Ayllu.Github.Client.Classrooms.ClassroomsRequestBuilder Classrooms
        {
            get => new global::Ayllu.Github.Client.Classrooms.ClassroomsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The codes_of_conduct property</summary>
        public global::Ayllu.Github.Client.Codes_of_conduct.Codes_of_conductRequestBuilder Codes_of_conduct
        {
            get => new global::Ayllu.Github.Client.Codes_of_conduct.Codes_of_conductRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The credentials property</summary>
        public global::Ayllu.Github.Client.Credentials.CredentialsRequestBuilder Credentials
        {
            get => new global::Ayllu.Github.Client.Credentials.CredentialsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The emojis property</summary>
        public global::Ayllu.Github.Client.Emojis.EmojisRequestBuilder Emojis
        {
            get => new global::Ayllu.Github.Client.Emojis.EmojisRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The enterprises property</summary>
        public global::Ayllu.Github.Client.Enterprises.EnterprisesRequestBuilder Enterprises
        {
            get => new global::Ayllu.Github.Client.Enterprises.EnterprisesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::Ayllu.Github.Client.Events.EventsRequestBuilder Events
        {
            get => new global::Ayllu.Github.Client.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The feeds property</summary>
        public global::Ayllu.Github.Client.Feeds.FeedsRequestBuilder Feeds
        {
            get => new global::Ayllu.Github.Client.Feeds.FeedsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The gists property</summary>
        public global::Ayllu.Github.Client.Gists.GistsRequestBuilder Gists
        {
            get => new global::Ayllu.Github.Client.Gists.GistsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The gitignore property</summary>
        public global::Ayllu.Github.Client.Gitignore.GitignoreRequestBuilder Gitignore
        {
            get => new global::Ayllu.Github.Client.Gitignore.GitignoreRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The installation property</summary>
        public global::Ayllu.Github.Client.Installation.InstallationRequestBuilder Installation
        {
            get => new global::Ayllu.Github.Client.Installation.InstallationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The issues property</summary>
        public global::Ayllu.Github.Client.Issues.IssuesRequestBuilder Issues
        {
            get => new global::Ayllu.Github.Client.Issues.IssuesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The licenses property</summary>
        public global::Ayllu.Github.Client.Licenses.LicensesRequestBuilder Licenses
        {
            get => new global::Ayllu.Github.Client.Licenses.LicensesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The markdown property</summary>
        public global::Ayllu.Github.Client.Markdown.MarkdownRequestBuilder Markdown
        {
            get => new global::Ayllu.Github.Client.Markdown.MarkdownRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The marketplace_listing property</summary>
        public global::Ayllu.Github.Client.Marketplace_listing.Marketplace_listingRequestBuilder Marketplace_listing
        {
            get => new global::Ayllu.Github.Client.Marketplace_listing.Marketplace_listingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The meta property</summary>
        public global::Ayllu.Github.Client.Meta.MetaRequestBuilder Meta
        {
            get => new global::Ayllu.Github.Client.Meta.MetaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The networks property</summary>
        public global::Ayllu.Github.Client.Networks.NetworksRequestBuilder Networks
        {
            get => new global::Ayllu.Github.Client.Networks.NetworksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notifications property</summary>
        public global::Ayllu.Github.Client.Notifications.NotificationsRequestBuilder Notifications
        {
            get => new global::Ayllu.Github.Client.Notifications.NotificationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The octocat property</summary>
        public global::Ayllu.Github.Client.Octocat.OctocatRequestBuilder Octocat
        {
            get => new global::Ayllu.Github.Client.Octocat.OctocatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The organizations property</summary>
        public global::Ayllu.Github.Client.Organizations.OrganizationsRequestBuilder Organizations
        {
            get => new global::Ayllu.Github.Client.Organizations.OrganizationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orgs property</summary>
        public global::Ayllu.Github.Client.Orgs.OrgsRequestBuilder Orgs
        {
            get => new global::Ayllu.Github.Client.Orgs.OrgsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The projects property</summary>
        public global::Ayllu.Github.Client.Projects.ProjectsRequestBuilder Projects
        {
            get => new global::Ayllu.Github.Client.Projects.ProjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rate_limit property</summary>
        public global::Ayllu.Github.Client.Rate_limit.Rate_limitRequestBuilder Rate_limit
        {
            get => new global::Ayllu.Github.Client.Rate_limit.Rate_limitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The repos property</summary>
        public global::Ayllu.Github.Client.Repos.ReposRequestBuilder Repos
        {
            get => new global::Ayllu.Github.Client.Repos.ReposRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The repositories property</summary>
        public global::Ayllu.Github.Client.Repositories.RepositoriesRequestBuilder Repositories
        {
            get => new global::Ayllu.Github.Client.Repositories.RepositoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Ayllu.Github.Client.Search.SearchRequestBuilder Search
        {
            get => new global::Ayllu.Github.Client.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The teams property</summary>
        public global::Ayllu.Github.Client.Teams.TeamsRequestBuilder Teams
        {
            get => new global::Ayllu.Github.Client.Teams.TeamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::Ayllu.Github.Client.User.UserRequestBuilder User
        {
            get => new global::Ayllu.Github.Client.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Ayllu.Github.Client.Users.UsersRequestBuilder Users
        {
            get => new global::Ayllu.Github.Client.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The versions property</summary>
        public global::Ayllu.Github.Client.Versions.VersionsRequestBuilder Versions
        {
            get => new global::Ayllu.Github.Client.Versions.VersionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The zen property</summary>
        public global::Ayllu.Github.Client.Zen.ZenRequestBuilder Zen
        {
            get => new global::Ayllu.Github.Client.Zen.ZenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ayllu.Github.Client.AylluGithubClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AylluGithubClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://api.github.com";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
        /// <summary>
        /// Get Hypermedia links to resources accessible in GitHub&apos;s REST API
        /// API method documentation <see href="https://docs.github.com/rest/meta/meta#github-api-root" />
        /// </summary>
        /// <returns>A <see cref="global::Ayllu.Github.Client.Models.Root"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Ayllu.Github.Client.Models.Root?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Ayllu.Github.Client.Models.Root> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Ayllu.Github.Client.Models.Root>(requestInfo, global::Ayllu.Github.Client.Models.Root.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get Hypermedia links to resources accessible in GitHub&apos;s REST API
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AylluGithubClientGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
