services:
  ayllu.api:
    image: ${DOCKER_REGISTRY-}aylluapi
    container_name: ayllu_api
    depends_on:
      - db
    build:
      context: .
      dockerfile: src/Ayllu.Api/Dockerfile
    networks:
      - ayllu-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ayllu_db
    environment:
      SA_PASSWORD: ${DBPASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - ayllu-network

networks:
  ayllu-network:
    driver: bridge