// <auto-generated/>
#pragma warning disable CS0618
using Ayllu.Github.Client.Repos.Item.Item.Releases.Assets.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Ayllu.Github.Client.Repos.Item.Item.Releases.Assets
{
    /// <summary>
    /// Builds and executes requests for operations under \repos\{owner-id}\{repo-id}\releases\assets
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AssetsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Ayllu.Github.Client.repos.item.item.releases.assets.item collection</summary>
        /// <param name="position">The unique identifier of the asset.</param>
        /// <returns>A <see cref="global::Ayllu.Github.Client.Repos.Item.Item.Releases.Assets.Item.WithAsset_ItemRequestBuilder"/></returns>
        public global::Ayllu.Github.Client.Repos.Item.Item.Releases.Assets.Item.WithAsset_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("asset_id", position);
                return new global::Ayllu.Github.Client.Repos.Item.Item.Releases.Assets.Item.WithAsset_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Ayllu.Github.Client.repos.item.item.releases.assets.item collection</summary>
        /// <param name="position">The unique identifier of the asset.</param>
        /// <returns>A <see cref="global::Ayllu.Github.Client.Repos.Item.Item.Releases.Assets.Item.WithAsset_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Ayllu.Github.Client.Repos.Item.Item.Releases.Assets.Item.WithAsset_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("asset_id", position);
                return new global::Ayllu.Github.Client.Repos.Item.Item.Releases.Assets.Item.WithAsset_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ayllu.Github.Client.Repos.Item.Item.Releases.Assets.AssetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AssetsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner%2Did}/{repo%2Did}/releases/assets", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ayllu.Github.Client.Repos.Item.Item.Releases.Assets.AssetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AssetsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner%2Did}/{repo%2Did}/releases/assets", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
