// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Ayllu.Github.Client.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Ayllu.Github.Client.Models.AddedToProjectIssueEvent"/>, <see cref="global::Ayllu.Github.Client.Models.AssignedIssueEvent"/>, <see cref="global::Ayllu.Github.Client.Models.ConvertedNoteToIssueIssueEvent"/>, <see cref="global::Ayllu.Github.Client.Models.DemilestonedIssueEvent"/>, <see cref="global::Ayllu.Github.Client.Models.LabeledIssueEvent"/>, <see cref="global::Ayllu.Github.Client.Models.LockedIssueEvent"/>, <see cref="global::Ayllu.Github.Client.Models.MilestonedIssueEvent"/>, <see cref="global::Ayllu.Github.Client.Models.MovedColumnInProjectIssueEvent"/>, <see cref="global::Ayllu.Github.Client.Models.RemovedFromProjectIssueEvent"/>, <see cref="global::Ayllu.Github.Client.Models.RenamedIssueEvent"/>, <see cref="global::Ayllu.Github.Client.Models.ReviewDismissedIssueEvent"/>, <see cref="global::Ayllu.Github.Client.Models.ReviewRequestedIssueEvent"/>, <see cref="global::Ayllu.Github.Client.Models.ReviewRequestRemovedIssueEvent"/>, <see cref="global::Ayllu.Github.Client.Models.UnassignedIssueEvent"/>, <see cref="global::Ayllu.Github.Client.Models.UnlabeledIssueEvent"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IssueEventForIssue : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Ayllu.Github.Client.Models.AddedToProjectIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Ayllu.Github.Client.Models.AddedToProjectIssueEvent? AddedToProjectIssueEvent { get; set; }
#nullable restore
#else
        public global::Ayllu.Github.Client.Models.AddedToProjectIssueEvent AddedToProjectIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Ayllu.Github.Client.Models.AssignedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Ayllu.Github.Client.Models.AssignedIssueEvent? AssignedIssueEvent { get; set; }
#nullable restore
#else
        public global::Ayllu.Github.Client.Models.AssignedIssueEvent AssignedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Ayllu.Github.Client.Models.ConvertedNoteToIssueIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Ayllu.Github.Client.Models.ConvertedNoteToIssueIssueEvent? ConvertedNoteToIssueIssueEvent { get; set; }
#nullable restore
#else
        public global::Ayllu.Github.Client.Models.ConvertedNoteToIssueIssueEvent ConvertedNoteToIssueIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Ayllu.Github.Client.Models.DemilestonedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Ayllu.Github.Client.Models.DemilestonedIssueEvent? DemilestonedIssueEvent { get; set; }
#nullable restore
#else
        public global::Ayllu.Github.Client.Models.DemilestonedIssueEvent DemilestonedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Ayllu.Github.Client.Models.LabeledIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Ayllu.Github.Client.Models.LabeledIssueEvent? LabeledIssueEvent { get; set; }
#nullable restore
#else
        public global::Ayllu.Github.Client.Models.LabeledIssueEvent LabeledIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Ayllu.Github.Client.Models.LockedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Ayllu.Github.Client.Models.LockedIssueEvent? LockedIssueEvent { get; set; }
#nullable restore
#else
        public global::Ayllu.Github.Client.Models.LockedIssueEvent LockedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Ayllu.Github.Client.Models.MilestonedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Ayllu.Github.Client.Models.MilestonedIssueEvent? MilestonedIssueEvent { get; set; }
#nullable restore
#else
        public global::Ayllu.Github.Client.Models.MilestonedIssueEvent MilestonedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Ayllu.Github.Client.Models.MovedColumnInProjectIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Ayllu.Github.Client.Models.MovedColumnInProjectIssueEvent? MovedColumnInProjectIssueEvent { get; set; }
#nullable restore
#else
        public global::Ayllu.Github.Client.Models.MovedColumnInProjectIssueEvent MovedColumnInProjectIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Ayllu.Github.Client.Models.RemovedFromProjectIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Ayllu.Github.Client.Models.RemovedFromProjectIssueEvent? RemovedFromProjectIssueEvent { get; set; }
#nullable restore
#else
        public global::Ayllu.Github.Client.Models.RemovedFromProjectIssueEvent RemovedFromProjectIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Ayllu.Github.Client.Models.RenamedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Ayllu.Github.Client.Models.RenamedIssueEvent? RenamedIssueEvent { get; set; }
#nullable restore
#else
        public global::Ayllu.Github.Client.Models.RenamedIssueEvent RenamedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Ayllu.Github.Client.Models.ReviewDismissedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Ayllu.Github.Client.Models.ReviewDismissedIssueEvent? ReviewDismissedIssueEvent { get; set; }
#nullable restore
#else
        public global::Ayllu.Github.Client.Models.ReviewDismissedIssueEvent ReviewDismissedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Ayllu.Github.Client.Models.ReviewRequestedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Ayllu.Github.Client.Models.ReviewRequestedIssueEvent? ReviewRequestedIssueEvent { get; set; }
#nullable restore
#else
        public global::Ayllu.Github.Client.Models.ReviewRequestedIssueEvent ReviewRequestedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Ayllu.Github.Client.Models.ReviewRequestRemovedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Ayllu.Github.Client.Models.ReviewRequestRemovedIssueEvent? ReviewRequestRemovedIssueEvent { get; set; }
#nullable restore
#else
        public global::Ayllu.Github.Client.Models.ReviewRequestRemovedIssueEvent ReviewRequestRemovedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Ayllu.Github.Client.Models.UnassignedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Ayllu.Github.Client.Models.UnassignedIssueEvent? UnassignedIssueEvent { get; set; }
#nullable restore
#else
        public global::Ayllu.Github.Client.Models.UnassignedIssueEvent UnassignedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Ayllu.Github.Client.Models.UnlabeledIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Ayllu.Github.Client.Models.UnlabeledIssueEvent? UnlabeledIssueEvent { get; set; }
#nullable restore
#else
        public global::Ayllu.Github.Client.Models.UnlabeledIssueEvent UnlabeledIssueEvent { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Ayllu.Github.Client.Models.IssueEventForIssue"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Ayllu.Github.Client.Models.IssueEventForIssue CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Ayllu.Github.Client.Models.IssueEventForIssue();
            result.AddedToProjectIssueEvent = new global::Ayllu.Github.Client.Models.AddedToProjectIssueEvent();
            result.AssignedIssueEvent = new global::Ayllu.Github.Client.Models.AssignedIssueEvent();
            result.ConvertedNoteToIssueIssueEvent = new global::Ayllu.Github.Client.Models.ConvertedNoteToIssueIssueEvent();
            result.DemilestonedIssueEvent = new global::Ayllu.Github.Client.Models.DemilestonedIssueEvent();
            result.LabeledIssueEvent = new global::Ayllu.Github.Client.Models.LabeledIssueEvent();
            result.LockedIssueEvent = new global::Ayllu.Github.Client.Models.LockedIssueEvent();
            result.MilestonedIssueEvent = new global::Ayllu.Github.Client.Models.MilestonedIssueEvent();
            result.MovedColumnInProjectIssueEvent = new global::Ayllu.Github.Client.Models.MovedColumnInProjectIssueEvent();
            result.RemovedFromProjectIssueEvent = new global::Ayllu.Github.Client.Models.RemovedFromProjectIssueEvent();
            result.RenamedIssueEvent = new global::Ayllu.Github.Client.Models.RenamedIssueEvent();
            result.ReviewDismissedIssueEvent = new global::Ayllu.Github.Client.Models.ReviewDismissedIssueEvent();
            result.ReviewRequestedIssueEvent = new global::Ayllu.Github.Client.Models.ReviewRequestedIssueEvent();
            result.ReviewRequestRemovedIssueEvent = new global::Ayllu.Github.Client.Models.ReviewRequestRemovedIssueEvent();
            result.UnassignedIssueEvent = new global::Ayllu.Github.Client.Models.UnassignedIssueEvent();
            result.UnlabeledIssueEvent = new global::Ayllu.Github.Client.Models.UnlabeledIssueEvent();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(AddedToProjectIssueEvent != null || AssignedIssueEvent != null || ConvertedNoteToIssueIssueEvent != null || DemilestonedIssueEvent != null || LabeledIssueEvent != null || LockedIssueEvent != null || MilestonedIssueEvent != null || MovedColumnInProjectIssueEvent != null || RemovedFromProjectIssueEvent != null || RenamedIssueEvent != null || ReviewDismissedIssueEvent != null || ReviewRequestedIssueEvent != null || ReviewRequestRemovedIssueEvent != null || UnassignedIssueEvent != null || UnlabeledIssueEvent != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(AddedToProjectIssueEvent, AssignedIssueEvent, ConvertedNoteToIssueIssueEvent, DemilestonedIssueEvent, LabeledIssueEvent, LockedIssueEvent, MilestonedIssueEvent, MovedColumnInProjectIssueEvent, RemovedFromProjectIssueEvent, RenamedIssueEvent, ReviewDismissedIssueEvent, ReviewRequestedIssueEvent, ReviewRequestRemovedIssueEvent, UnassignedIssueEvent, UnlabeledIssueEvent);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Ayllu.Github.Client.Models.AddedToProjectIssueEvent>(null, AddedToProjectIssueEvent, AssignedIssueEvent, ConvertedNoteToIssueIssueEvent, DemilestonedIssueEvent, LabeledIssueEvent, LockedIssueEvent, MilestonedIssueEvent, MovedColumnInProjectIssueEvent, RemovedFromProjectIssueEvent, RenamedIssueEvent, ReviewDismissedIssueEvent, ReviewRequestedIssueEvent, ReviewRequestRemovedIssueEvent, UnassignedIssueEvent, UnlabeledIssueEvent);
        }
    }
}
#pragma warning restore CS0618
