// <auto-generated/>
#pragma warning disable CS0618
using Ayllu.Github.Client.Orgs.Item.Actions.HostedRunners.Images.GithubOwned;
using Ayllu.Github.Client.Orgs.Item.Actions.HostedRunners.Images.Partner;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Ayllu.Github.Client.Orgs.Item.Actions.HostedRunners.Images
{
    /// <summary>
    /// Builds and executes requests for operations under \orgs\{org}\actions\hosted-runners\images
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ImagesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The githubOwned property</summary>
        public global::Ayllu.Github.Client.Orgs.Item.Actions.HostedRunners.Images.GithubOwned.GithubOwnedRequestBuilder GithubOwned
        {
            get => new global::Ayllu.Github.Client.Orgs.Item.Actions.HostedRunners.Images.GithubOwned.GithubOwnedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The partner property</summary>
        public global::Ayllu.Github.Client.Orgs.Item.Actions.HostedRunners.Images.Partner.PartnerRequestBuilder Partner
        {
            get => new global::Ayllu.Github.Client.Orgs.Item.Actions.HostedRunners.Images.Partner.PartnerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ayllu.Github.Client.Orgs.Item.Actions.HostedRunners.Images.ImagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImagesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orgs/{org}/actions/hosted-runners/images", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ayllu.Github.Client.Orgs.Item.Actions.HostedRunners.Images.ImagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImagesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orgs/{org}/actions/hosted-runners/images", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
