name: "Bug"
description: "Reporte um bug ou mal comportamento vinculada à uma ou um conjunto de features"
title: "[BUG] "
labels: ["bug"]
projects: ["default"]
assignees: []
type: "BUG"

body:
  - type: input
    id: api-version
    attributes:
      label: Versão da API 
      description: "Versão da apí onde o erro ocorre (obter em /api/v1/healthcheck/host). e.g.: 0.0.1.0"
      placeholder: "0.0.1.0"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Ambiente
      description: |
        Em qual ambiente o erro ocorre. Para confirmar o ambiente, execute uma requisição em GET /api/v1/healthcheck/host
      options:
        - Development (Visual Studio)
        - Docker (docker-compose.yml)
        - Development (https://dev.ayllu.remotecodehub.com/)
        - Test (https://test.ayllu.remotecodehub.com/)
        - Production (https://ayllu.org/)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detalhes da Implementação
      description: |
        Descreva o que deve ser implementado nesta feature.
      placeholder: "Explicar claramente o escopo da feature."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Exemplo mínimo reproduzível
      description: |
        Por favor, forneça [o menor trecho de código completo](https://stackoverflow.com/help/minimal-reproducible-example) da requisilção éfetuada na API. Uma maneira fácil de começar é copiar [código de exemplo](https://github.com/remotecodehub/ayllu/tree/main/src/sdk/Ayllu.Api.Sdk/README.md) e o modificar de acordo com o seu cenário. 
                
        Se o resultado for muito extensivo, ou muitos arquivos, por favor:

        - _Anexe_ (não copie e cole) para esse campo, _ou_
        - Transforme em uma [Gist](https://gist.github.com) e referencie aqui o link da mesma, _ou_
        - Disponibilize um link para um repositório publico, novo ou existente com o código de reprodução desse bug e referencie o repositório aqui.
    validations:
      required: true


