// <auto-generated/>
#pragma warning disable CS0618
using Ayllu.Github.Client.Projects.Columns;
using Ayllu.Github.Client.Projects.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Ayllu.Github.Client.Projects
{
    /// <summary>
    /// Builds and executes requests for operations under \projects
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProjectsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The columns property</summary>
        public global::Ayllu.Github.Client.Projects.Columns.ColumnsRequestBuilder Columns
        {
            get => new global::Ayllu.Github.Client.Projects.Columns.ColumnsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Ayllu.Github.Client.projects.item collection</summary>
        /// <param name="position">The unique identifier of the project.</param>
        /// <returns>A <see cref="global::Ayllu.Github.Client.Projects.Item.WithProject_ItemRequestBuilder"/></returns>
        [Obsolete("")]
        public global::Ayllu.Github.Client.Projects.Item.WithProject_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("project_id", position);
                return new global::Ayllu.Github.Client.Projects.Item.WithProject_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Ayllu.Github.Client.projects.item collection</summary>
        /// <param name="position">The unique identifier of the project.</param>
        /// <returns>A <see cref="global::Ayllu.Github.Client.Projects.Item.WithProject_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Ayllu.Github.Client.Projects.Item.WithProject_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("project_id", position);
                return new global::Ayllu.Github.Client.Projects.Item.WithProject_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ayllu.Github.Client.Projects.ProjectsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ayllu.Github.Client.Projects.ProjectsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
