// <auto-generated/>
#pragma warning disable CS0618
using Ayllu.Mobile.Client.Api.V1.Dialectics.Friends;
using Ayllu.Mobile.Client.Api.V1.Dialectics.Item;
using Ayllu.Mobile.Client.Api.V1.Dialectics.Mine;
using Ayllu.Mobile.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Ayllu.Mobile.Client.Api.V1.Dialectics
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v1\dialectics
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DialecticsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The friends property</summary>
        public global::Ayllu.Mobile.Client.Api.V1.Dialectics.Friends.FriendsRequestBuilder Friends
        {
            get => new global::Ayllu.Mobile.Client.Api.V1.Dialectics.Friends.FriendsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mine property</summary>
        public global::Ayllu.Mobile.Client.Api.V1.Dialectics.Mine.MineRequestBuilder Mine
        {
            get => new global::Ayllu.Mobile.Client.Api.V1.Dialectics.Mine.MineRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Ayllu.Mobile.Client.api.v1.dialectics.item collection</summary>
        /// <param name="position">O identificador único da dialética a ser retornada.</param>
        /// <returns>A <see cref="global::Ayllu.Mobile.Client.Api.V1.Dialectics.Item.DialecticItemRequestBuilder"/></returns>
        public global::Ayllu.Mobile.Client.Api.V1.Dialectics.Item.DialecticItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("dialectic%2Did", position);
                return new global::Ayllu.Mobile.Client.Api.V1.Dialectics.Item.DialecticItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ayllu.Mobile.Client.Api.V1.Dialectics.DialecticsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DialecticsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/dialectics", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ayllu.Mobile.Client.Api.V1.Dialectics.DialecticsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DialecticsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v1/dialectics", rawUrl)
        {
        }
        /// <summary>
        /// Cria uma nova dialética
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> PostAsync(global::Ayllu.Mobile.Client.Models.CreateDialecticRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> PostAsync(global::Ayllu.Mobile.Client.Models.CreateDialecticRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Cria uma nova dialética
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Ayllu.Mobile.Client.Models.CreateDialecticRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Ayllu.Mobile.Client.Models.CreateDialecticRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Ayllu.Mobile.Client.Api.V1.Dialectics.DialecticsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Ayllu.Mobile.Client.Api.V1.Dialectics.DialecticsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Ayllu.Mobile.Client.Api.V1.Dialectics.DialecticsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DialecticsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
