<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyVersion>0.0.1.0</AssemblyVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>  
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.1" />
    <PackageReference Include="Quartz" Version="3.15.1" />
    <PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.15.1" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.15.1" />
    <PackageReference Include="Quartz.Serialization.Json" Version="3.15.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ayllu.Web.Application\Ayllu.Web.Application.csproj" />
    <ProjectReference Include="..\Ayllu.Web.Domain\Ayllu.Web.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Jobs\" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Communication/Email/TemplatesFiles/**/*.html" />
  </ItemGroup>
</Project>
