// <auto-generated/>
#pragma warning disable CS0618
using Ayllu.Github.Client.Repos.Item.Item.Actions.Artifacts;
using Ayllu.Github.Client.Repos.Item.Item.Actions.Cache;
using Ayllu.Github.Client.Repos.Item.Item.Actions.Caches;
using Ayllu.Github.Client.Repos.Item.Item.Actions.Jobs;
using Ayllu.Github.Client.Repos.Item.Item.Actions.Oidc;
using Ayllu.Github.Client.Repos.Item.Item.Actions.OrganizationSecrets;
using Ayllu.Github.Client.Repos.Item.Item.Actions.OrganizationVariables;
using Ayllu.Github.Client.Repos.Item.Item.Actions.Permissions;
using Ayllu.Github.Client.Repos.Item.Item.Actions.Runners;
using Ayllu.Github.Client.Repos.Item.Item.Actions.Runs;
using Ayllu.Github.Client.Repos.Item.Item.Actions.Secrets;
using Ayllu.Github.Client.Repos.Item.Item.Actions.Variables;
using Ayllu.Github.Client.Repos.Item.Item.Actions.Workflows;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Ayllu.Github.Client.Repos.Item.Item.Actions
{
    /// <summary>
    /// Builds and executes requests for operations under \repos\{owner-id}\{repo-id}\actions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The artifacts property</summary>
        public global::Ayllu.Github.Client.Repos.Item.Item.Actions.Artifacts.ArtifactsRequestBuilder Artifacts
        {
            get => new global::Ayllu.Github.Client.Repos.Item.Item.Actions.Artifacts.ArtifactsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cache property</summary>
        public global::Ayllu.Github.Client.Repos.Item.Item.Actions.Cache.CacheRequestBuilder Cache
        {
            get => new global::Ayllu.Github.Client.Repos.Item.Item.Actions.Cache.CacheRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The caches property</summary>
        public global::Ayllu.Github.Client.Repos.Item.Item.Actions.Caches.CachesRequestBuilder Caches
        {
            get => new global::Ayllu.Github.Client.Repos.Item.Item.Actions.Caches.CachesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The jobs property</summary>
        public global::Ayllu.Github.Client.Repos.Item.Item.Actions.Jobs.JobsRequestBuilder Jobs
        {
            get => new global::Ayllu.Github.Client.Repos.Item.Item.Actions.Jobs.JobsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oidc property</summary>
        public global::Ayllu.Github.Client.Repos.Item.Item.Actions.Oidc.OidcRequestBuilder Oidc
        {
            get => new global::Ayllu.Github.Client.Repos.Item.Item.Actions.Oidc.OidcRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The organizationSecrets property</summary>
        public global::Ayllu.Github.Client.Repos.Item.Item.Actions.OrganizationSecrets.OrganizationSecretsRequestBuilder OrganizationSecrets
        {
            get => new global::Ayllu.Github.Client.Repos.Item.Item.Actions.OrganizationSecrets.OrganizationSecretsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The organizationVariables property</summary>
        public global::Ayllu.Github.Client.Repos.Item.Item.Actions.OrganizationVariables.OrganizationVariablesRequestBuilder OrganizationVariables
        {
            get => new global::Ayllu.Github.Client.Repos.Item.Item.Actions.OrganizationVariables.OrganizationVariablesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The permissions property</summary>
        public global::Ayllu.Github.Client.Repos.Item.Item.Actions.Permissions.PermissionsRequestBuilder Permissions
        {
            get => new global::Ayllu.Github.Client.Repos.Item.Item.Actions.Permissions.PermissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The runners property</summary>
        public global::Ayllu.Github.Client.Repos.Item.Item.Actions.Runners.RunnersRequestBuilder Runners
        {
            get => new global::Ayllu.Github.Client.Repos.Item.Item.Actions.Runners.RunnersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The runs property</summary>
        public global::Ayllu.Github.Client.Repos.Item.Item.Actions.Runs.RunsRequestBuilder Runs
        {
            get => new global::Ayllu.Github.Client.Repos.Item.Item.Actions.Runs.RunsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The secrets property</summary>
        public global::Ayllu.Github.Client.Repos.Item.Item.Actions.Secrets.SecretsRequestBuilder Secrets
        {
            get => new global::Ayllu.Github.Client.Repos.Item.Item.Actions.Secrets.SecretsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The variables property</summary>
        public global::Ayllu.Github.Client.Repos.Item.Item.Actions.Variables.VariablesRequestBuilder Variables
        {
            get => new global::Ayllu.Github.Client.Repos.Item.Item.Actions.Variables.VariablesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The workflows property</summary>
        public global::Ayllu.Github.Client.Repos.Item.Item.Actions.Workflows.WorkflowsRequestBuilder Workflows
        {
            get => new global::Ayllu.Github.Client.Repos.Item.Item.Actions.Workflows.WorkflowsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ayllu.Github.Client.Repos.Item.Item.Actions.ActionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner%2Did}/{repo%2Did}/actions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ayllu.Github.Client.Repos.Item.Item.Actions.ActionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner%2Did}/{repo%2Did}/actions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
