// <auto-generated/>
#pragma warning disable CS0618
using Ayllu.Github.Client.Projects.Columns.Cards;
using Ayllu.Github.Client.Projects.Columns.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Ayllu.Github.Client.Projects.Columns
{
    /// <summary>
    /// Builds and executes requests for operations under \projects\columns
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ColumnsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cards property</summary>
        public global::Ayllu.Github.Client.Projects.Columns.Cards.CardsRequestBuilder Cards
        {
            get => new global::Ayllu.Github.Client.Projects.Columns.Cards.CardsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Ayllu.Github.Client.projects.columns.item collection</summary>
        /// <param name="position">The unique identifier of the column.</param>
        /// <returns>A <see cref="global::Ayllu.Github.Client.Projects.Columns.Item.WithColumn_ItemRequestBuilder"/></returns>
        [Obsolete("")]
        public global::Ayllu.Github.Client.Projects.Columns.Item.WithColumn_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("column_id", position);
                return new global::Ayllu.Github.Client.Projects.Columns.Item.WithColumn_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Ayllu.Github.Client.projects.columns.item collection</summary>
        /// <param name="position">The unique identifier of the column.</param>
        /// <returns>A <see cref="global::Ayllu.Github.Client.Projects.Columns.Item.WithColumn_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Ayllu.Github.Client.Projects.Columns.Item.WithColumn_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("column_id", position);
                return new global::Ayllu.Github.Client.Projects.Columns.Item.WithColumn_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ayllu.Github.Client.Projects.Columns.ColumnsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ColumnsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/columns", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ayllu.Github.Client.Projects.Columns.ColumnsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ColumnsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/columns", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
