// <auto-generated/>
#pragma warning disable CS0618
using Ayllu.Github.Client.Search.Code;
using Ayllu.Github.Client.Search.Commits;
using Ayllu.Github.Client.Search.Issues;
using Ayllu.Github.Client.Search.Labels;
using Ayllu.Github.Client.Search.Repositories;
using Ayllu.Github.Client.Search.Topics;
using Ayllu.Github.Client.Search.Users;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Ayllu.Github.Client.Search
{
    /// <summary>
    /// Builds and executes requests for operations under \search
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SearchRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The code property</summary>
        public global::Ayllu.Github.Client.Search.Code.CodeRequestBuilder Code
        {
            get => new global::Ayllu.Github.Client.Search.Code.CodeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The commits property</summary>
        public global::Ayllu.Github.Client.Search.Commits.CommitsRequestBuilder Commits
        {
            get => new global::Ayllu.Github.Client.Search.Commits.CommitsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The issues property</summary>
        public global::Ayllu.Github.Client.Search.Issues.IssuesRequestBuilder Issues
        {
            get => new global::Ayllu.Github.Client.Search.Issues.IssuesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The labels property</summary>
        public global::Ayllu.Github.Client.Search.Labels.LabelsRequestBuilder Labels
        {
            get => new global::Ayllu.Github.Client.Search.Labels.LabelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The repositories property</summary>
        public global::Ayllu.Github.Client.Search.Repositories.RepositoriesRequestBuilder Repositories
        {
            get => new global::Ayllu.Github.Client.Search.Repositories.RepositoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The topics property</summary>
        public global::Ayllu.Github.Client.Search.Topics.TopicsRequestBuilder Topics
        {
            get => new global::Ayllu.Github.Client.Search.Topics.TopicsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Ayllu.Github.Client.Search.Users.UsersRequestBuilder Users
        {
            get => new global::Ayllu.Github.Client.Search.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ayllu.Github.Client.Search.SearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ayllu.Github.Client.Search.SearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SearchRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
