<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Ayllu.Composition\Ayllu.Composition.csproj" />
    <ProjectReference Include="..\Ayllu.Application\Ayllu.Application.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" Version="10.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MudBlazor" Version="9.8.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.20" />
    <PackageReference Include="Scalar.AspNetCore.Microsoft" Version="2.16.20" /> 
  </ItemGroup>
  
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>8ffad36d-cdcb-4eb0-afdf-c93a38506081</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
    <GenerateClient Condition="'$(GenerateClient)' == ''">false</GenerateClient>
    <OpenApiGenerateDocuments>$(GenerateClient)</OpenApiGenerateDocuments>
    <OpenApiGenerateDocumentsOnBuild>$(GenerateClient)</OpenApiGenerateDocumentsOnBuild>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <Version>1.0.0.0</Version>
  </PropertyGroup>


  <Target Name="AddMigration">
    <PropertyGroup>
      <MigrationName>$(Name)</MigrationName>
    </PropertyGroup>

    <Error Condition="'$(MigrationName)' == ''" Text="Missing migration name. Example: dotnet build -t:AddMigration &quot;-p:Name=MyMigration&quot;" />

    <Exec Command="dotnet ef migrations add $(MigrationName) -s . -p ..\Ayllu.Infrastructure\ --output-dir ..\Ayllu.Infrastructure\Persistence\Migrations" />
  </Target>
  <Target Name="GenerateKiotaSDK" AfterTargets="Build" Condition="'$(Configuration)' == 'Debug' And '$(GenerateClient)' == 'true'">
    <PropertyGroup>
      <OpenApiSpecPath>$(MSBuildProjectDirectory)\obj\$(MSBuildProjectName).json</OpenApiSpecPath>
      <SdkOutputDir>$(MSBuildProjectDirectory)\..\..\sdk\Ayllu.Sdk\Cli\</SdkOutputDir>
      <GetDocumentTool>$(PkgMicrosoft_Extensions_ApiDescription_Server)\tools\GetDocument.InsideMicrosoft.exe</GetDocumentTool>
    </PropertyGroup>

    <Message Text="[OpenAPI] Extracting OpenAPI spec to: $(OpenApiSpecPath)" Importance="high" />

    <Exec Command="dotnet tool run dotnet-getdocument --assembly &quot;$(TargetPath)&quot; --output &quot;$(OpenApiSpecPath)&quot; --file-name &quot;$(TargetName)&quot;" ContinueOnError="true" StandardOutputImportance="low" />

    <Message Text="[Kiota] Generating API SDK client at: $(SdkOutputDir)..." Importance="high" />

    <Exec Command="kiota generate -l CSharp -c AylluClient -n Ayllu.Sdk.Cli -d &quot;$(OpenApiSpecPath)&quot; -o &quot;$(SdkOutputDir)&quot; --clean-output" ContinueOnError="false" />

    <Message Text="[Kiota] SDK successfully generated!" Importance="high" />
  </Target>
</Project>
