// <auto-generated/>
#pragma warning disable CS0618
using Ayllu.Github.Client.Orgs.Item.Copilot.Billing;
using Ayllu.Github.Client.Orgs.Item.Copilot.Metrics;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Ayllu.Github.Client.Orgs.Item.Copilot
{
    /// <summary>
    /// Builds and executes requests for operations under \orgs\{org}\copilot
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CopilotRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The billing property</summary>
        public global::Ayllu.Github.Client.Orgs.Item.Copilot.Billing.BillingRequestBuilder Billing
        {
            get => new global::Ayllu.Github.Client.Orgs.Item.Copilot.Billing.BillingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metrics property</summary>
        public global::Ayllu.Github.Client.Orgs.Item.Copilot.Metrics.MetricsRequestBuilder Metrics
        {
            get => new global::Ayllu.Github.Client.Orgs.Item.Copilot.Metrics.MetricsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ayllu.Github.Client.Orgs.Item.Copilot.CopilotRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CopilotRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orgs/{org}/copilot", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ayllu.Github.Client.Orgs.Item.Copilot.CopilotRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CopilotRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/orgs/{org}/copilot", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
