name: "Build"

on:
  push:
    branches:
      - '**'   # qualquer branch
      - main   # e explicitamente a main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

  pull_request:
    branches:
      - '**'   # qualquer branch de destino do PR
      - main   # e explicitamente a main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.304

      - name: Instalar workloads MAUI
        run: dotnet workload install maui

      - name: Configurar Xcode 16.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Restore
        run: dotnet restore Ayllu.sln

      - name: Build
        run: dotnet build --configuration Release --no-restore Ayllu.sln

    # - name: Test
    #   run: dotnet test Ayllu.sln
