name: "Build"

on:
  push: 
    branches: 
      - main   
  pull_request:
    types:
       - opened
       - synchronize
       - reopened 
  workflow_dispatch:

jobs: 
  client:
    name: "Build (${{ matrix.target.framework }}${{ matrix.target.runtime && format(' - {0}', matrix.target.runtime) }})"
    runs-on: ${{ matrix.target.os }}
    strategy:
      matrix:
        target:
          - { os: ubuntu-latest,framework: net10.0-android }
          - { os: macos-26, framework: net10.0-ios, runtime: iossimulator-arm64 }
          - { os: macos-26, framework: net10.0-maccatalyst, runtime: maccatalyst-arm64 }
          - { os: windows-latest, framework: net10.0-windows10.0.19041.0, runtime: win-x64 }
      fail-fast: false
     
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x
          
      - name: Instalar workloads MAUI
        run: ${{ matrix.target.os != 'ubuntu-latest' && 'dotnet workload install maui' || 'dotnet workload install maui-android' }}

      - name: Setup Java JDK (Android only)
        if: matrix.target.framework == 'net10.0-android'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Select Xcode Version (Apple platforms only)
        if: matrix.target.os == 'macos-26' 
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          xcodebuild -version

      - name: Restore workloads
        run: dotnet workload restore

      - name: Restore packages
        working-directory: ${{ github.workspace }}/src/client/Ayllu/
        run: dotnet restore Ayllu.csproj  ${{ matrix.target.runtime && format('--runtime {0}', matrix.target.runtime) }} 

      - name: Build
        working-directory: ${{ github.workspace }}/src/client/Ayllu/
        run: dotnet build Ayllu.csproj --configuration Release --framework ${{ matrix.target.framework }} ${{ matrix.target.runtime && format('--runtime {0}', matrix.target.runtime) }} --no-restore

  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x
 
      - name: Restore packages
        working-directory: ${{ github.workspace }}/src/server/Ayllu
        run: dotnet restore Ayllu.csproj

      - name: Build
        working-directory: ${{ github.workspace }}/src/server/Ayllu
        run: dotnet build Ayllu.csproj --configuration Release --framework net10.0 --no-restore


  
   


  